name: Upload PDF to GitHub artifacts
permissions:
  contents: write
on:
  push:
    branches: [ test-ci ]
jobs:
  build-examples:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install dependencies
          run: apk update && apk add texmf-dist texlive texmf-dist-latexextra nodejs

        - name: Build
          run: cp -r latexPackage/utc-*/* rapport && cd rapport && pdflatex -interaction=nonstopmode -halt-on-error rapport.tex

        - name: Create index.html
          run: mkdir public && echo "<!DOCTYPE html><html lang='fr'><head><meta charset='UTF-8'><meta http-equiv='refresh' content='5;url=../rapport/rapport.pdf'><title>Redirection vers le PDF</title></head></html>" > public/index.html

        - name: Deploy to GitHub Pages
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            FOLDER: public

        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: rapport.pdf
            path: rapport/rapport.pdf

            
