name: Upload PDF to GitHub artifacts
permissions:
  contents: write
on:
  push:
    branches: [ main ]
jobs:
  build-examples:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install dependencies
          run: apk update && apk add texmf-dist texlive texmf-dist-latexextra nodejs

        - name: Build
          run: cp -r latexPackage/utc-*/* rapport && cd rapport && pdflatex -interaction=nonstopmode -halt-on-error rapport.tex

        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: rapport.pdf
            path: rapport/rapport.pdf
